name: dondurma_mobil
version: 0.1.0
publish_to: none
description: Dondurma üreticisi için yönetim ve sipariş Flutter uygulaması

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
